auto: true
source: vernnobile.github.com/fontforge-GUI
pygments: true
markdown: rdiscount
permalink: none
url: http://vernnobile.github.com/fontforge-GUI
title: The FontForge GUI
subtitle: Improving the fontforge graphical user interface